-- 建表
create table public.user_configs (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  data json null,
  updated_at text null,
  user_id uuid not null,
  constraint user_configs_pkey primary key (id),
  constraint user_configs_user_id_key unique (user_id)
) TABLESPACE pg_default;

-- 启用行级安全（RLS）
alter table public.user_configs enable row level security;

drop policy if exists "user_configs_select_own" on public.user_configs;
drop policy if exists "user_configs_insert_own" on public.user_configs;
drop policy if exists "user_configs_update_own" on public.user_configs;

create policy "user_configs_select_own"
on public.user_configs
for select
using (auth.uid() = user_id);

create policy "user_configs_insert_own"
on public.user_configs
for insert
with check (auth.uid() = user_id);

create policy "user_configs_update_own"
on public.user_configs
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

-- 增量更新函数
create or replace function public.update_user_config_partial(payload jsonb)
returns void
language plpgsql
security definer
set search_path = public
as
$$
begin
update public.user_configs
set data = ((coalesce(data::jsonb, '{}'::jsonb) || payload)::json),
    updated_at = now()
where user_id = auth.uid();
end;
$$;

grant execute on function public.update_user_config_partial(jsonb) to authenticated;
grant execute on function public.update_user_config_partial(jsonb) to service_role;

-- 开启实时订阅 Publication（必须，否则 Supabase Realtime 无法监听 user_configs 表变更）
drop publication if exists supabase_realtime for table public.user_configs;
create publication supabase_realtime for table public.user_configs;

-- v1.0.0 版本更新关联板块表

-- 创建 fund_related 表
create table public.fund_related (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  fund_code character varying null,
  related_sector text null,
  constraint fund_related_pkey primary key (id),
  constraint fund_related_fund_code_key unique (fund_code)
) TABLESPACE pg_default;


-- 1. 开启 RLS
ALTER TABLE fund_related ENABLE ROW LEVEL SECURITY;

-- 2. 仅允许已登录用户查询
CREATE POLICY "Allow authenticated users to select fund_related"
ON fund_related
FOR SELECT
TO authenticated
USING (auth.uid() IS NOT NULL);

-- 创建 fund_secid 表
create table public.fund_secid (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  related_sector text null,
  secid character varying null,
  constraint fund_secid_pkey primary key (id)
) TABLESPACE pg_default;

-- 1. 开启 RLS
ALTER TABLE fund_secid ENABLE ROW LEVEL SECURITY;

-- 2. 仅允许已登录用户查询
CREATE POLICY "Allow authenticated users to select fund_secid"
ON fund_secid
FOR SELECT
TO authenticated
USING (auth.uid() IS NOT NULL);
